---

- hosts: vm1
  vars:
    target: /tmp/file.txt

  tasks:
    - name: Discover the State of file
      command: grep "is really an"  {{target}}
      register: grep_state
      tags:
        - create
        - destroy
      ignore_errors: true

    - name: Show the state of file
      debug:
        var: grep_state.rc

    - name: An Idempotent copy command
      copy:
        src: file.txt 
        dest: '{{target}}'
      when: grep_state.rc != 0
      tags:
        - create
        - destroy

    - name: Modify the file
      command: sed - ie 's/is/is really an/' {{target}}
      when: grep_state.rc != 0
      tags:
        - create
        - destroy

    - name: Remove the file
      file:
        path: '{{target}}'
        state: absent
      tags:
        - destroy



