---
- hosts: localhost
  connection: local
  vars:
    gw: 10.0.0.1
    netaddr: 255.255.224.0

  tasks:
    - set_fact: net="{{gw}}/{{netaddr}}"
    - set_fact: net1="{{net | ipaddr( 'host/prefix' ) }}"
    - set_fact: intnet="{{gw| ipaddr('int')}}"
    - set_fact: ipaddr1="{{ intnet|ipv4('address')}}"
    - debug:
        msg: "Network address are {{net}}, {{net1}} & {{intnet}} & {{ipaddr1}}"


