---
- hosts: vm4
  tasks:
    - name: Install needed network manager libs
      ansible.builtin.package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
        state: present

    - name: Add a new interface on hosts
      nmcli:
        conn_name: my-eth1
        ifname: eth1
        type: ethernet
        ipv4: 192.0.2.100/24
        gw4:  192.0.2.1
        state: "{{file_state}}"
        autoconnect: yes
