---

- hosts: vm
  tasks:
    - name: Update all existing Yum packages on Ubuntu machines
      yum:
        name: '*'
        state: "{{ pkg_state }}"
      when: ansible_os_family == "Ubuntu" 
      tags: 
        - Update all Packages

- hosts: vm
  tasks:
    - name: Update Python on machines
      yum:
        name: python
        state: "{{ pkg_state }}"
      when: ansible_os_family == "RedHat"
      tags: 
        - Update Python       


- hosts: vm
  vars:
    packages: [ruby,docker]
  tasks:
    - name: Install packages using yum on Redhat machines
      yum:
        name: '{{packages}}'
        state: '{{pkg_state}}'
      when: ansible_os_family == "RedHat"
      tags: 
        - Install Ruby and Docker