---
- hosts: vm
  tasks:
  - name: embed the secure password in a file
    template:
      src: templates/password_file.j2
      dest: /tmp/password_file
      mode: 0600
    tags:
      - create
  - name: clean up the secure passwords file
    file:
      name: /tmp/password_file
      state: absent
    tags:
      - destroy  
  - name: debug the password that was encrypted
    debug:
      msg: 'The actual password is {{password}}'
    tags:
      - create
      - destroy